[package]
name = "divvun-api"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@technocreatives.com>", "Rostislav Raykov <rostislav@technocreatives.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
actix = "0.7"
serde = "1.0.88"
serde_json = "1.0.38"
serde_derive = "1.0.88"
divvunspell = { git = "https://github.com/divvun/divvunspell" }
futures = "*"
failure = "*"
hashbrown = "*"
sentry = "0.15.1"
sentry-actix = "0.15.1"
dotenv = "0.13.0"
dotenv_codegen = "0.11.0"