[package]
name = "divvun-grammarcheck-api"
version = "0.1.0"
authors = ["Rostislav Raykov <z@zbrox.org>"]
edition = "2018"

[dependencies]
gotham = "0.3.0"
gotham_derive = "0.3.0"
serde = { version = "1.0.87", features = ["derive"] }
serde_json = "1.0.38"
hyper = "0.12.24"
mime = "0.3.13"
divvunspell = { git = "https://github.com/divvun/divvunspell.git" }