[package]
name = "divvun-api"
version = "0.2.0"
authors = [
    "Brendan Molloy <brendan@technocreatives.com>", 
    "Rostislav Raykov <rostislav@technocreatives.com>",
    "Eike Siewertsen <eike@technocreatives.com>",
    "projektir <oprojektir@gmail.com>",
]

edition = "2018"

[dependencies]
actix-web = "1.0.0-beta.3"
actix = "0.8"
log = "0.4.6"
env_logger = "0.6"
juniper = "0.11.1"
serde = "1.0.88"
serde_json = "1.0.38"
serde_derive = "1.0.88"
divvunspell = { git = "https://github.com/divvun/divvunspell", branch="develop" }
futures = "0.1"
failure = "0.1.5"
hashbrown = "0.3.0"
toml = "0.5.0"
directories = "1.0"
regex = "1"
csv = "1.0.5"
clap = "2.33.0"
notify = "4.0.12"
